let stockProductos = [
    {id: 1, nombre: "Buzo 1", tipo: "buzo", cantidad: 1, desc: "Un buzo que con estilo unico", precio: 5000, talle: "L", img: './img/buzo.png'},
    {id: 2, nombre: "Buzo 2", tipo: "buzo", cantidad: 1, desc: "Un buzo con estilo unico", precio: 5000, talle: "L", img: './img/buzo.png'},
    {id: 3, nombre: "Buzo 3", tipo: "buzo", cantidad: 1, desc: "Un buzo con estilo unico", precio: 5000, talle: "M", img: './img/buzo.png'},
    {id: 4, nombre: "Buzo 4", tipo: "buzo", cantidad: 1, desc: "Un buzo con estilo unico", precio: 5000, talle: "M", img: './img/buzo.png'},
    {id: 5, nombre: "Buzo 5", tipo: "buzo", cantidad: 1, desc: "Un buzo con estilo unico", precio: 5000, talle: "S", img: './img/buzo.png'},
    {id: 6, nombre: "Buzo 6", tipo: "buzo", cantidad: 1, desc: "Un buzo con estilo unico", precio: 5000, talle: "S", img: './img/buzo.png'},
    {id: 7, nombre: "Remera 1", tipo: "remera", cantidad: 1, desc: "Una remera con estilo unico", precio: 3500, talle: "L", img: './img/remera.png'},
    {id: 8, nombre: "Remera 2", tipo: "remera", cantidad: 1, desc: "Una remera con estilo unico", precio: 3500, talle: "L", img: './img/remera.png'},
    {id: 9, nombre: "Remera 3", tipo: "remera", cantidad: 1, desc: "Una remera con estilo unico", precio: 3500, talle: "M", img: './img/remera.png'},
    {id: 10, nombre: "Remera 4", tipo: "remera", cantidad: 1, desc: "Una remera con estilo unico", precio: 3500, talle: "M", img: './img/remera.png'},
    {id: 11, nombre: "Remera 5", tipo: "remera", cantidad: 1,desc: "Una remera con estilo unico", precio: 3500, talle: "S", img: './img/remera.png'},
    {id: 12, nombre: "Remera 6", tipo: "remera", cantidad: 1, desc: "Una remera con estilo unico", precio: 3500, talle: "S", img: './img/remera.png'},
    {id: 13, nombre: "jean 1", tipo: "jean", cantidad: 1, desc: "Un jean con estilo unico", precio: 12000, talle: "L", img: './img/jean.png'},
    {id: 14, nombre: "jean 2", tipo: "jean", cantidad: 1, desc: "Un jean con estilo unico", precio: 12000, talle: "S", img: './img/jean.png'},
    {id: 15, nombre: "jean 3", tipo: "jean", cantidad: 1, desc: "Un jean con estilo unico", precio: 12000, talle: "L", img: './img/jean.png'},
    {id: 16, nombre: "jean 4", tipo: "jean", cantidad: 1, desc: "Un jean con estilo unico", precio: 12000, talle: "S", img: './img/jean.png'},
    {id: 17, nombre: "jean 5", tipo: "jean", cantidad: 1, desc: "Un jean con estilo unico", precio: 12000, talle: "S", img: './img/jean.png'},
    {id: 18, nombre: "jean 6", tipo: "jean", cantidad: 1, desc: "Un jean con estilo unico", precio: 12000, talle: "M", img: './img/jean.png'},
    {id: 19, nombre: "zapatillas 1", tipo: "zapatillas", cantidad: 1, desc: "Unas zapatillas con estilo unico", precio: 25000, talle: "L", img: './img/zapatillas.png'},
    {id: 20, nombre: "zapatillas 2", tipo: "zapatillas", cantidad: 1, desc: "Unas zapatillas con estilo unico", precio: 25000, talle: "M", img: './img/zapatillas.png'},
    {id: 21, nombre: "zapatillas 3", tipo: "zapatillas", cantidad: 1, desc: "Unas zapatillas con estilo unico", precio: 25000, talle: "M", img: './img/zapatillas.png'},
    {id: 22, nombre: "zapatillas 4", tipo: "zapatillas", cantidad: 1, desc: "Unas zapatillas con estilo unico", precio: 25000, talle: "M", img: './img/zapatillas.png'},
    {id: 23, nombre: "zapatillas 5", tipo: "zapatillas", cantidad: 1, desc: "Unas zapatillas con estilo unico", precio: 25000, talle: "S", img: './img/zapatillas.png'},
    {id: 24, nombre: "zapatillas 6", tipo: "zapatillas", cantidad: 1, desc: "Unas zapatillas con estilo unico", precio: 25000, talle: "S", img: './img/zapatillas.png'},
]